name: Deploy Frontend to Amazon S3

on:
  push:
    branches: [ "dev" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: myapp-frontend-dev-20260429 # [주의] 배포할 S3 버킷 이름으로 변경해야 합니다.

jobs:
  deploy:
    name: Build and Deploy to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 1. Node.js 환경 설정
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # 2. 패키지 설치
    - name: Install Dependencies
      run: npm install

    # 3. React 프로젝트 빌드
    - name: Build Project
      run: npm run build
      env:
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

    # 4. AWS 인증 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 5. S3에 빌드된 파일 업로드 (동기화)
    - name: Deploy to Amazon S3
      run: |
        aws s3 sync build/ s3://${{ env.S3_BUCKET_NAME }} --delete

